#application.properties? ??
#server.port=8081
#spring.datasource.url=jdbc:mariadb://localhost:3306/member
#spring.datasource.username=root
#spring.datasource.password=1234

#????? ????.
#server:
#  port: 8081
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa:
    database: mysql
#    innoDB 엔진사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
#    스키마는 사전생성 필요
    generate-ddl: true
    hibernate:
#      create옵션은 매번 table을 drop후 생성
#      update옵션은 변경사항만 alter를 적용
#      validate는 실제DB와의 차이만을 check
#      실무에서는 update 또는 validate를 사용
#      create : 모든 DDL 변경사항 반영, 컬럼추가(컬럼길이변경) 모두 가능
#      update : 컬럼 길이변경 불가능, raw DDL 커리문으로 변경
#      validate : 실제DB와의 차이만을 체크, DB 직접 반영안됨
      ddl-auto: update
#    jpa가 자동으로 쿼리를 실행할때, 쿼리가 console 창에 보여지도록
    show_sql: true

#mapper 파일 위치
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

#---
#


#server:
#  port: 8081
#spring:
#  profiles:
#    active: prod
#  datasource:
#    url: url=jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234